### PR TITLE
Rename from RebirthDB to RethinkDB :smile:

### PR DESCRIPTION
**Pull request by grandquista**

### CODE REVIEW

**Comment by thelinuxlich** [comment]
WAT I didnt invite you to the org?

**Comment by rushmorem** [comment]
> WAT I didnt invite you to the org?

You did. I'm already a member of the RethinkDB org but for some reason I don't have write access to this particular repo.

**Comment by thelinuxlich** [comment]
It's fixed, now you can do your magic, apologies for the inconvenience :)

**Comment by rushmorem** [comment]
> It's fixed

Thanks :)

> apologies for the inconvenience

It's OK

**Pull request merged**
